version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['time_zone'] = 'Etc/GMT'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'gitlab@example.com'
        gitlab_rails['gitlab_email_display_name'] = 'gitlab'
        gitlab_rails['gitlab_email_reply_to'] = 'reply@example.com'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'email-smtp.xx-xxxx-0.amazonaws.com'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = 'AKIXXXXXXXXXXXXXXXXX'
        gitlab_rails['smtp_password'] = 'AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        gitlab_rails['smtp_domain'] = 'example.com'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
    ports:
      - '9080:80'
      #- '443:443'
      #- '22:22'
    volumes:
      - 'gitlab-etc:/etc/gitlab'
      - 'gitlab-log:/var/log/gitlab'
      - 'gitlab-opt:/var/opt/gitlab'
volumes:
  gitlab-etc:
  gitlab-log:
  gitlab-opt:
