version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
    ports:
      - '9080:80'
      #- '443:443'
      #- '22:22'
    volumes:
      - 'gitlab-etc:/etc/gitlab'
      - 'gitlab-log:/var/log/gitlab'
      - 'gitlab-opt:/var/opt/gitlab'
volumes:
  gitlab-etc:
  gitlab-log:
  gitlab-opt:
